2025-03-05 02:58:04,640 INFO: Starting application in development mode [in F:\PythonII\Dating\app\utils\logging.py:43]
2025-03-05 02:58:05,391 WARNING:  * Debugger is active! [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:05,400 INFO:  * Debugger PIN: 132-194-637 [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:09,349 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:09] "[32mGET / HTTP/1.1[0m" 302 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:09,377 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:09] "[35m[1mGET /login HTTP/1.1[0m" 500 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:09,563 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:09] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:09,571 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:09] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:09,699 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:09] "GET /login?__debugger__=yes&cmd=resource&f=console.png&s=vAF4FdKQPJE2mRiFJoQe HTTP/1.1" 200 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:09,701 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:09] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:09,928 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:09] "[36mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:58:10,179 INFO: 127.0.0.1 - - [05/Mar/2025 02:58:10] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
2025-03-05 02:59:00,510 INFO:  * Detected change in 'F:\\PythonII\\Dating\\app\\auth\\routes.py', reloading [in F:\PythonII\Dating\.venv\Lib\site-packages\werkzeug\_internal.py:97]
